### ISSUE TITLE
How do we address Material-UI dependency?

### ISSUE THREAD

**Issue by juancarlosfarah** [graasp/graasp-ui#1]
Not sure what the best way is to "force" Material-UI as a peer dependency. Here is what the author of the library mentions:

https://github.com/transitive-bullshit/create-react-library#material-ui

**Comment by juancarlosfarah** [comment]
@pyphilia reports issues with the theme. Need to look into it and test with graasp/graasp-desktop.

**Comment by pyphilia** [comment]
commit https://github.com/graasp/graasp-ui/pull/3/commits/d73bd0ed26c6e9dfb8fa9d7e09b63f858d2e89c2 solve the theme problem by moving material dependencies to peer dependencies only.
