### ISSUE TITLE
Fix Item Header display inconsistency 

### ISSUE THREAD

**Issue by spaenleh** [graasp/graasp-ui#107]
The Item Header has some inconsistencies when displaying action buttons:
Edit, Share and Show player view are 44x48 pixels while all the others are 48x48 pixels
Before:
<img width="381" alt="Screenshot 2022-03-22 at 14 22 52" src="https://user-images.githubusercontent.com/39373170/159494770-018658ed-8e11-4dc0-86de-ffee3bb162e8.png">
Expected:
<img width="388" alt="Screenshot 2022-03-22 at 14 22 36" src="https://user-images.githubusercontent.com/39373170/159494818-d5b332aa-3a84-4519-a8a6-df0893fe6dfb.png">

This seems to be caused by using the `fontSize="small"` prop on the icon buttons for the first 3 buttons.

@pyphilia Is it ok to remove this prop (which results in the second screenshot) ?

**Comment by pyphilia** [comment]
@spaenleh Good catch. I think we can go with all buttons being `medium` (so remove the prop yes).

**Comment by spaenleh** [comment]
Forgot to link to PR ... 

![woops](https://media.giphy.com/media/abittW9YasaxSimk0E/giphy-downsized.gif)
