### ISSUE TITLE
Add emoji picker to TextEditor.

### ISSUE THREAD

**Issue by pyphilia** [graasp/graasp-ui#166]
It would be great for our TextEditor component to propose an emoji picker.
Does react-quill has an extension for that?

**Comment by Duri01** [comment]
I found some solutions on the net
 
Can you assign me this issue ? Thansk :)

**Comment by pyphilia** [comment]
@Duri01 Thanks for tackling this!

**Comment by Duri01** [comment]
Hello, I start working on it. How can I test it ? thanks a lot.

**Comment by pyphilia** [comment]
@Duri01 this PR https://github.com/graasp/graasp-ui/pull/163 will soon be merged (beginning of next week), and will contain Storybook, an ideal way to display the components!

**Comment by Duri01** [comment]
Hello, thanks for informations :)
