### ISSUE TITLE
Add collapse to h5p

### ISSUE THREAD

**Issue by pyphilia** [graasp/graasp-ui#195]
Add a prop to `H5PItem.tsx` called `showCollapse` to enable or disable the Collapse wrapper component.

Similar to this 
https://github.com/graasp/graasp-player/blob/780ff89e07fd23d7783c94e9751aead6091a2098/src/components/common/Item.js#L322 
but this behavior should happen in graasp-ui.

**Comment by juancarlosfarah** [comment]
@MalinSvenberg, this should be a good issue with which to get started too.
