### ISSUE TITLE
Deploy to Github Pages using artifacts

### ISSUE THREAD

**Issue by spaenleh** [graasp/graasp-ui#337]
Current implementation pushes deployement files to the `gh-pages` branch and then uses github's ability to deploy from a branch with an automated workflow to push the static site to GitHub Pages.

There is an alternative (currently in beta but successfully tested) that uses the github artifacts to directly upload the site to github pages without cluttering a branch in the repo. Props to @morganridel for showing me this.

**Comment by morganridel** [comment]
Nice! :tada:
