### ISSUE TITLE
Behaviour of platform switch button of current platform

### ISSUE THREAD

**Issue by dialexo** [graasp/graasp-ui#353]
What should the button of the current platform do? It currently does nothing (`#`), but should it redirect to the home of the respective platform?

- It may be counter-intuitive because the other buttons in the switch redirect to the current item in the other platforms
- however it would be more consistent, e.g. to quickly return to the home of each platform (instead of using the main logo, which may not be obvious)

To implement this new behaviour change the host map on each platform to add the current platform itself:

- For instance in library:

  https://github.com/graasp/graasp-library/blob/ce2143ab099ce9438e5f92154007812417794eae/src/components/common/HeaderNavigation.tsx#LL92C1-L95C4

  should become
  ```diff
    export const platformsHostsMap = defaultHostsMapper({
      [Platform.Builder]: HOST_MAP.builder,
      [Platform.Player]: HOST_MAP.player,
  +   [Platform.Library]: HOST_MAP.library,
    });
  ```

- Similarly in builder:

  https://github.com/graasp/graasp-builder/blob/c31bae81acf8c49ca8c038dc530a2d841ea96822/src/components/main/Main.tsx#L45-L48

  ```diff
    export const platformsHostsMap = defaultHostsMapper({
      [Platform.Player]: HOST_MAP.player,
      [Platform.Library]: HOST_MAP.library,
  +    [Platform.Builder]: HOST_MAP.builder,
    });
  ```

- Same thing in Player, but need to add the root path env var

**Comment by dialexo** [comment]
Thank you, so we decided to enable the "return to home of platform" behaviour on all buttons for now.

**Comment by pyphilia** [comment]
closed with https://github.com/graasp/graasp-builder/pull/736
https://github.com/graasp/graasp-library/pull/341
https://github.com/graasp/graasp-player/pull/306
